# Generated by Django 4.2.2 on 2023-06-22 15:16

from django.core.management import call_command
from django.db import migrations


def func(apps, schema_editor):
    call_command("loaddata", "social_media_service.json")


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("social_media_service", "0002_initial"),
    ]

    operations = [
        migrations.RunPython(func, reverse_func),
    ]
